[build]
  command = "npm run build"
  publish = "dist/hormon-calculator-frontend/browser"

[[redirects]]
  from = "/api/*"
  to = "http://188.138.38.172:8080/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
